import sys
from PyQt6.QtGui import QFont
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QApplication, QMessageBox, QDialog, QLineEdit, QStackedWidget, QMainWindow, QLabel, QTableWidget,QPushButton, QHBoxLayout, QWidget, QVBoxLayout

class VPuesto(QWidget):
    def __init__(self):
        super(VPuesto, self).__init__()
        self.fila = 0
        self.columna = 2
        self.generartabla()

    def generartabla(self):
        self.tableWidget = QTableWidget()
        self.tableWidget.setRowCount(self.fila)
        self.tableWidget.setColumnCount(self.columna)  

        self.tableWidget.setStyleSheet("QTableWidget { background-color: black; }")
        self.tableWidget.setStyleSheet("QTableWidget::item { border: .2px solid black; }")
        column_width = 140
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setVisible(False)
        for i in range(self.columna):
            self.tableWidget.setColumnWidth(i, column_width)

        self.agregar = QPushButton('Agregar Puesto')
        self.agregar.setFont(QFont('Bond', 8))
        self.agregar.setFixedSize(90, 23)

        self.detalles=QPushButton('Detalles')
        self.detalles.setFont(QFont('Bond', 8))
        self.detalles.setFixedSize(90, 23)

        self.editar = QPushButton('Editar')
        self.editar.setFont(QFont('Bond', 8))
        self.editar.setFixedSize(90, 23)

        blayout = QHBoxLayout()
        blayout.addWidget(self.agregar)
        blayout.addWidget(self.detalles)
        blayout.addWidget(self.editar)

        layout = QVBoxLayout(self)
        layout.addLayout(blayout)
        layout.addWidget(self.tableWidget)
        #self.agregar.clicked.connect(self.agregar_fila)
    

    def agregar_fila(self, nombre):
        self.fila += 1
        self.tableWidget.setRowCount(self.fila)

        puesto = QLabel(f'{nombre}')
        puesto.setAlignment(Qt.AlignmentFlag.AlignCenter)           
        self.tableWidget.setCellWidget(self.fila - 1, 0, puesto)

        borrar = QPushButton('Borrar')
        self.tableWidget.setCellWidget(self.fila - 1, 1, borrar)
        borrar.clicked.connect(self.borra)

    def borra(self):
        index = self.tableWidget.indexAt(self.sender().pos())
        if index.isValid():
            fila = index.row()
            self.tableWidget.removeRow(fila)
            self.fila -= 1

    def borrar_cancelar(self):
        if self.fila > 0:
            self.fila -= 1
            self.tableWidget.setRowCount(self.fila)

class Pag2(QWidget):
    def __init__(self):
        super(Pag2, self).__init__()

        self.nom_l=QLabel(self)
        self.nom_l.setText('Nombre del Puesto')
        self.nom_l.setFont(QFont('Bond',10))
        self.nom_l.move(20,20)
        self.nom_t=QLineEdit(self)
        self.nom_t.setText('')
        self.nom_t.setFont(QFont('Bond',8))
        self.nom_t.move(20,40)
        self.nom_t.setFixedSize(750,20)

        self.codp_l=QLabel(self)
        self.codp_l.setText('Codigo de Puesto')
        self.codp_l.setFont(QFont('Bond',10))
        self.codp_l.move(20,60)
        self.codpt_t=QLineEdit(self)
        self.codpt_t.setText('')
        self.codpt_t.setFont(QFont('Bond',8))
        self.codpt_t.move(20,78)
        self.codpt_t.setFixedSize(400,20)

        self.area_l=QLabel(self)
        self.area_l.setText('Area de adscripcion')
        self.area_l.setFont(QFont('Bond',10))
        self.area_l.move(425,60)
        self.area_t=QLineEdit(self)
        self.area_t.setText('')
        self.area_t.setFont(QFont('Bond',8))
        self.area_t.move(425,78)
        self.area_t.setFixedSize(345,20)

#
        self.super_l=QLabel(self)
        self.super_l.setText('Puesto del Jefe Superior')
        self.super_l.setFont(QFont('Bond',10))
        self.super_l.move(20,100)
        self.super_t=QLineEdit(self)
        self.super_t.setText('')
        self.super_t.setFont(QFont('Bond',8))
        self.super_t.move(20,118)
        self.super_t.setFixedSize(750,20)

        self.jornada_l=QLabel(self)
        self.jornada_l.setText('Jornada')
        self.jornada_l.setFont(QFont('Bond',10))
        self.jornada_l.move(20,138)
        self.jornada_t=QLineEdit(self)
        self.jornada_t.setText('')
        self.jornada_t.setFont(QFont('Bond',8))
        self.jornada_t.move(20,155)
        self.jornada_t.setFixedSize(450,20)

        self.remuneracion_l=QLabel(self)
        self.remuneracion_l.setText('Remuneracion Mensual')
        self.remuneracion_l.setFont(QFont('Bond',10))
        self.remuneracion_l.move(475,138)
        self.remuneracion_t=QLineEdit(self)
        self.remuneracion_t.setText('')
        self.remuneracion_t.setFont(QFont('Bond',8))
        self.remuneracion_t.move(475,155)
        self.remuneracion_t.setFixedSize(295,20)

        self.prestaciones_l=QLabel(self)
        self.prestaciones_l.setText('Prestaciones')
        self.prestaciones_l.setFont(QFont('Bond',10))
        self.prestaciones_l.move(20,178)
        self.prestaciones_t=QLineEdit(self)
        self.prestaciones_t.setText('')
        self.prestaciones_t.setFont(QFont('Bond',8))
        self.prestaciones_t.move(20,196)
        self.prestaciones_t.setFixedSize(750,20)

        self.descripccion_l=QLabel(self)
        self.descripccion_l.setText('Descripcion General')
        self.descripccion_l.setFont(QFont('Bond',10))
        self.descripccion_l.move(20,218)
        self.descripccion_t=QLineEdit(self)
        self.descripccion_t.setText('')
        self.descripccion_t.setFont(QFont('Bond',8))
        self.descripccion_t.move(20,236)
        self.descripccion_t.setFixedSize(750,20)

        self.funciones_l=QLabel(self)
        self.funciones_l.setText('Funciones')
        self.funciones_l.setFont(QFont('Bond',10))
        self.funciones_l.move(20,258)
        self.funciones_t=QLineEdit(self)
        self.funciones_t.setText('')
        self.funciones_t.setFont(QFont('Bond',8))
        self.funciones_t.move(20,273)
        self.funciones_t.setFixedSize(750,20)

        self.edad_l=QLabel(self)
        self.edad_l.setText('Edad')
        self.edad_l.setFont(QFont('Bond',10))
        self.edad_l.move(20,298)
        self.edad_t=QLineEdit(self)
        self.edad_t.setText('')
        self.edad_t.setFont(QFont('Bond',8))
        self.edad_t.move(20,316)
        self.edad_t.setFixedSize(225,20)

        self.sexo_l=QLabel(self)
        self.sexo_l.setText('Sexo')
        self.sexo_l.setFont(QFont('Bond',10))
        self.sexo_l.move(255,298)
        self.sexo_t=QLineEdit(self)
        self.sexo_t.setText('')
        self.sexo_t.setFont(QFont('Bond',8))
        self.sexo_t.move(255,316)
        self.sexo_t.setFixedSize(225,20)

        self.civil_l=QLabel(self)
        self.civil_l.setText('Estado Civil')
        self.civil_l.setFont(QFont('Bond',10))
        self.civil_l.move(485,298)
        self.civil_t=QLineEdit(self)
        self.civil_t.setText('')
        self.civil_t.setFont(QFont('Bond',8))
        self.civil_t.move(485,316)
        self.civil_t.setFixedSize(283,20)

        self.escolaridad_l=QLabel(self)
        self.escolaridad_l.setText('Escolaridad')
        self.escolaridad_l.setFont(QFont('Bond',10))
        self.escolaridad_l.move(20,340)
        self.escolaridad_t=QLineEdit(self)
        self.escolaridad_t.setText('')
        self.escolaridad_t.setFont(QFont('Bond',8))
        self.escolaridad_t.move(20,358)
        self.escolaridad_t.setFixedSize(225,20)

        self.gradoa_l=QLabel(self)
        self.gradoa_l.setText('Grado Avance')
        self.gradoa_l.setFont(QFont('Bond',10))
        self.gradoa_l.move(255,340)
        self.gradoa_t=QLineEdit(self)
        self.gradoa_t.setText('')
        self.gradoa_t.setFont(QFont('Bond',8))
        self.gradoa_t.move(255,358)
        self.gradoa_t.setFixedSize(225,20)

        self.carrera_l=QLabel(self)
        self.carrera_l.setText('Carrera')
        self.carrera_l.setFont(QFont('Bond',10))
        self.carrera_l.move(485,340)
        self.carrera_t=QLineEdit(self)
        self.carrera_t.setText('')
        self.carrera_t.setFont(QFont('Bond',8))
        self.carrera_t.move(485,358)
        self.carrera_t.setFixedSize(283,20)

        self.botona_pag=QPushButton(self)
        self.botona_pag.setText('Continuar')
        self.botona_pag.setFont(QFont('Bond',8))
        self.botona_pag.move(370, 390)
        self.botona_pag.setFixedSize(70, 20)

        self.botoncancelar=QPushButton(self)
        self.botoncancelar.setText('Cancelar')
        self.botona_pag.setFont(QFont('Bond',8))
        self.botoncancelar. move(110,390)
        self.botoncancelar.setFixedSize(70, 20)

    def limpiar(self):
        for child_widget in self.findChildren(QLineEdit):
            child_widget.clear()

class Pag3(QWidget):
    def __init__(self):
        super(Pag3, self).__init__()
        self.experiencia_l=QLabel(self)
        self.experiencia_l.setText('Experiencia')
        self.experiencia_l.setFont(QFont('Bond',10))
        self.experiencia_l.move(20,20)
        self.experiencia_t=QLineEdit(self)
        self.experiencia_t.setText('')
        self.experiencia_t.setFont(QFont('Bond',8))
        self.experiencia_t.move(20,40)
        self.experiencia_t.setFixedSize(750,20)

        self.conocimentos_l=QLabel(self)
        self.conocimentos_l.setText('Conocimentos')
        self.conocimentos_l.setFont(QFont('Bond',10))
        self.conocimentos_l.move(20,60)
        self.conocimentos_t=QLineEdit(self)
        self.conocimentos_t.setText('')
        self.conocimentos_t.setFont(QFont('Bond',8))
        self.conocimentos_t.move(20,78)
        self.conocimentos_t.setFixedSize(750,20)

        self.mequipo_l=QLabel(self)
        self.mequipo_l.setText('ManejoEquipo')
        self.mequipo_l.setFont(QFont('Bond',10))
        self.mequipo_l.move(20,100)
        self.mequipo_t=QLineEdit(self)
        self.mequipo_t.setText('')
        self.mequipo_t.setFont(QFont('Bond',8))
        self.mequipo_t.move(20,118)
        self.mequipo_t.setFixedSize(750,20)

        self.rfisicos_l=QLabel(self)
        self.rfisicos_l.setText('Requisitos Fisicos')
        self.rfisicos_l.setFont(QFont('Bond',10))
        self.rfisicos_l.move(20,138)
        self.rfisicos_t=QLineEdit(self)
        self.rfisicos_t.setText('')
        self.rfisicos_t.setFont(QFont('Bond',8))
        self.rfisicos_t.move(20,155)
        self.rfisicos_t.setFixedSize(750,20)

        self.rpsicologicos_l=QLabel(self)
        self.rpsicologicos_l.setText('Requisitos Psicologicos')
        self.rpsicologicos_l.setFont(QFont('Bond',10))
        self.rpsicologicos_l.move(20,178)
        self.rpsicologicos_t=QLineEdit(self)
        self.rpsicologicos_t.setText('')
        self.rpsicologicos_t.setFont(QFont('Bond',8))
        self.rpsicologicos_t.move(20,196)
        self.rpsicologicos_t.setFixedSize(750,20)

        self.responsabilidades_l=QLabel(self)
        self.responsabilidades_l.setText('Responsabilidades')
        self.responsabilidades_l.setFont(QFont('Bond',10))
        self.responsabilidades_l.move(20,218)
        self.responsabilidades_t=QLineEdit(self)
        self.responsabilidades_t.setText('')
        self.responsabilidades_t.setFont(QFont('Bond',8))
        self.responsabilidades_t.move(20,236)
        self.responsabilidades_t.setFixedSize(750,20)

        self.condiciones_l=QLabel(self)
        self.condiciones_l.setText('Condiciones de Trabajo')
        self.condiciones_l.setFont(QFont('Bond',10))
        self.condiciones_l.move(20,258)
        self.condiciones_t=QLineEdit(self)
        self.condiciones_t.setText('')
        self.condiciones_t.setFont(QFont('Bond',8))
        self.condiciones_t.move(20,273)
        self.condiciones_t.setFixedSize(750,20)

        self.idiomas_l=QLabel(self)
        self.idiomas_l.setText('Idiomas')
        self.idiomas_l.setFont(QFont('Bond',10))
        self.idiomas_l.move(20,298)
        self.idiomast_t=QLineEdit(self)
        self.idiomast_t.setText('')
        self.idiomast_t.setFont(QFont('Bond',8))
        self.idiomast_t.move(20,316)
        self.idiomast_t.setFixedSize(400,20)

        self.habilidades_l=QLabel(self)
        self.habilidades_l.setText('Habilidades')
        self.habilidades_l.setFont(QFont('Bond',10))
        self.habilidades_l.move(425,298)
        self.habilidades_t=QLineEdit(self)
        self.habilidades_t.setText('')
        self.habilidades_t.setFont(QFont('Bond',8))
        self.habilidades_t.move(425,316)
        self.habilidades_t.setFixedSize(345,20)

        self.botona_pag=QPushButton(self)
        self.botona_pag.setText('Finalizar y Guardar')
        self.botona_pag.setFont(QFont('Bond',8))
        self.botona_pag.move(370, 350)
        self.botona_pag.setFixedSize(120, 25)

        self.botonregreso=QPushButton(self)
        self.botonregreso.setText('Regresar')
        self.botonregreso.setFont(QFont('Bond',8))
        self.botonregreso.move(30, 350)
        self.botonregreso.setFixedSize(120, 25)

    def limpiar(self):
        for child_widget in self.findChildren(QLineEdit):
            child_widget.clear()

class ventanaDetalles(QWidget):

    def __init__(self):
        super(ventanaDetalles, self).__init__()
        self.nom_l=QLabel(self)
        self.nom_l.setText('Nombre del Puesto')
        self.nom_l.setFont(QFont('Bond',10))
        self.nom_l.move(20,20)
        self.nom_t=QLineEdit(self)
        self.nom_t.setText('')
        self.nom_t.setFont(QFont('Bond',8))
        self.nom_t.move(20,40)
        self.nom_t.setFixedSize(750,20)
        #self.nom_t.setText('Juan')
        self.nom_t.setReadOnly(True)

        self.codp_l=QLabel(self)
        self.codp_l.setText('Codigo de Puesto')
        self.codp_l.setFont(QFont('Bond',10))
        self.codp_l.move(20,60)
        self.codpt_t=QLineEdit(self)
        self.codpt_t.setText('')
        self.codpt_t.setFont(QFont('Bond',8))
        self.codpt_t.move(20,78)
        self.codpt_t.setFixedSize(400,20)
        self.codpt_t.setReadOnly(True)

        self.area_l=QLabel(self)
        self.area_l.setText('Area de adscripcion')
        self.area_l.setFont(QFont('Bond',10))
        self.area_l.move(425,60)
        self.area_t=QLineEdit(self)
        self.area_t.setText('')
        self.area_t.setFont(QFont('Bond',8))
        self.area_t.move(425,78)
        self.area_t.setFixedSize(345,20)
        self.area_t.setReadOnly(True)

        self.super_l=QLabel(self)
        self.super_l.setText('Puesto del Jefe Superior')
        self.super_l.setFont(QFont('Bond',10))
        self.super_l.move(20,100)
        self.super_t=QLineEdit(self)
        self.super_t.setText('')
        self.super_t.setFont(QFont('Bond',8))
        self.super_t.move(20,118)
        self.super_t.setFixedSize(750,20)
        self.super_t.setReadOnly(True)

        self.jornada_l=QLabel(self)
        self.jornada_l.setText('Jornada')
        self.jornada_l.setFont(QFont('Bond',10))
        self.jornada_l.move(20,138)
        self.jornada_t=QLineEdit(self)
        self.jornada_t.setText('')
        self.jornada_t.setFont(QFont('Bond',8))
        self.jornada_t.move(20,155)
        self.jornada_t.setFixedSize(450,20)
        self.jornada_t.setReadOnly(True)

        self.remuneracion_l=QLabel(self)
        self.remuneracion_l.setText('Remuneracion Mensual')
        self.remuneracion_l.setFont(QFont('Bond',10))
        self.remuneracion_l.move(475,138)
        self.remuneracion_t=QLineEdit(self)
        self.remuneracion_t.setText('')
        self.remuneracion_t.setFont(QFont('Bond',8))
        self.remuneracion_t.move(475,155)
        self.remuneracion_t.setFixedSize(295,20)
        self.remuneracion_t.setReadOnly(True)

        self.prestaciones_l=QLabel(self)
        self.prestaciones_l.setText('Prestaciones')
        self.prestaciones_l.setFont(QFont('Bond',10))
        self.prestaciones_l.move(20,178)
        self.prestaciones_t=QLineEdit(self)
        self.prestaciones_t.setText('')
        self.prestaciones_t.setFont(QFont('Bond',8))
        self.prestaciones_t.move(20,196)
        self.prestaciones_t.setFixedSize(750,20)
        self.prestaciones_t.setReadOnly(True)

        self.descripccion_l=QLabel(self)
        self.descripccion_l.setText('Descripcion General')
        self.descripccion_l.setFont(QFont('Bond',10))
        self.descripccion_l.move(20,218)
        self.descripccion_t=QLineEdit(self)
        self.descripccion_t.setText('')
        self.descripccion_t.setFont(QFont('Bond',8))
        self.descripccion_t.move(20,236)
        self.descripccion_t.setFixedSize(750,20)
        self.descripccion_t.setReadOnly(True)

        self.funciones_l=QLabel(self)
        self.funciones_l.setText('Funciones')
        self.funciones_l.setFont(QFont('Bond',10))
        self.funciones_l.move(20,258)
        self.funciones_t=QLineEdit(self)
        self.funciones_t.setText('')
        self.funciones_t.setFont(QFont('Bond',8))
        self.funciones_t.move(20,273)
        self.funciones_t.setFixedSize(750,20)
        self.funciones_t.setReadOnly(True)

        self.edad_l=QLabel(self)
        self.edad_l.setText('Edad')
        self.edad_l.setFont(QFont('Bond',10))
        self.edad_l.move(20,298)
        self.edad_t=QLineEdit(self)
        self.edad_t.setText('')
        self.edad_t.setFont(QFont('Bond',8))
        self.edad_t.move(20,316)
        self.edad_t.setFixedSize(225,20)
        self.edad_t.setReadOnly(True)

        self.sexo_l=QLabel(self)
        self.sexo_l.setText('Sexo')
        self.sexo_l.setFont(QFont('Bond',10))
        self.sexo_l.move(255,298)
        self.sexo_t=QLineEdit(self)
        self.sexo_t.setText('')
        self.sexo_t.setFont(QFont('Bond',8))
        self.sexo_t.move(255,316)
        self.sexo_t.setFixedSize(225,20)
        self.sexo_t.setReadOnly(True)

        self.civil_l=QLabel(self)
        self.civil_l.setText('Estado Civil')
        self.civil_l.setFont(QFont('Bond',10))
        self.civil_l.move(485,298)
        self.civil_t=QLineEdit(self)
        self.civil_t.setText('')
        self.civil_t.setFont(QFont('Bond',8))
        self.civil_t.move(485,316)
        self.civil_t.setFixedSize(283,20)
        self.civil_t.setReadOnly(True)

        self.escolaridad_l=QLabel(self)
        self.escolaridad_l.setText('Escolaridad')
        self.escolaridad_l.setFont(QFont('Bond',10))
        self.escolaridad_l.move(20,340)
        self.escolaridad_t=QLineEdit(self)
        self.escolaridad_t.setText('')
        self.escolaridad_t.setFont(QFont('Bond',8))
        self.escolaridad_t.move(20,358)
        self.escolaridad_t.setFixedSize(225,20)
        self.escolaridad_t.setReadOnly(True)

        self.gradoa_l=QLabel(self)
        self.gradoa_l.setText('Grado Avance')
        self.gradoa_l.setFont(QFont('Bond',10))
        self.gradoa_l.move(255,340)
        self.gradoa_t=QLineEdit(self)
        self.gradoa_t.setText('')
        self.gradoa_t.setFont(QFont('Bond',8))
        self.gradoa_t.move(255,358)
        self.gradoa_t.setFixedSize(225,20)
        self.gradoa_t.setReadOnly(True)

        self.carrera_l=QLabel(self)
        self.carrera_l.setText('Carrera')
        self.carrera_l.setFont(QFont('Bond',10))
        self.carrera_l.move(485,340)
        self.carrera_t=QLineEdit(self)
        self.carrera_t.setText('')
        self.carrera_t.setFont(QFont('Bond',8))
        self.carrera_t.move(485,358)
        self.carrera_t.setFixedSize(283,20)
        self.carrera_t.setReadOnly(True)

        self.botona_pag=QPushButton(self)
        self.botona_pag.setText('Siguiente Pagina')
        self.botona_pag.setFont(QFont('Bond',8))
        self.botona_pag.move(370, 390)
        self.botona_pag.setFixedSize(100, 25)

        self.botoncancelar=QPushButton(self)
        self.botoncancelar.setText('Salir')
        self.botona_pag.setFont(QFont('Bond',8))
        self.botoncancelar. move(110,390)
        self.botoncancelar.setFixedSize(70, 25)

class ventanadetalles2(QWidget):
    def __init__(self):
        super(ventanadetalles2, self).__init__()

        self.experiencia_l=QLabel(self)
        self.experiencia_l.setText('Experiencia')
        self.experiencia_l.setFont(QFont('Bond',10))
        self.experiencia_l.move(20,20)
        self.experiencia_t=QLineEdit(self)
        self.experiencia_t.setText('')
        self.experiencia_t.setFont(QFont('Bond',8))
        self.experiencia_t.move(20,40)
        self.experiencia_t.setFixedSize(750,20)

        self.conocimentos_l=QLabel(self)
        self.conocimentos_l.setText('Conocimentos')
        self.conocimentos_l.setFont(QFont('Bond',10))
        self.conocimentos_l.move(20,60)
        self.conocimentos_t=QLineEdit(self)
        self.conocimentos_t.setText('')
        self.conocimentos_t.setFont(QFont('Bond',8))
        self.conocimentos_t.move(20,78)
        self.conocimentos_t.setFixedSize(750,20)

        self.mequipo_l=QLabel(self)
        self.mequipo_l.setText('ManejoEquipo')
        self.mequipo_l.setFont(QFont('Bond',10))
        self.mequipo_l.move(20,100)
        self.mequipo_t=QLineEdit(self)
        self.mequipo_t.setText('')
        self.mequipo_t.setFont(QFont('Bond',8))
        self.mequipo_t.move(20,118)
        self.mequipo_t.setFixedSize(750,20)

        self.rfisicos_l=QLabel(self)
        self.rfisicos_l.setText('Requisitos Fisicos')
        self.rfisicos_l.setFont(QFont('Bond',10))
        self.rfisicos_l.move(20,138)
        self.rfisicos_t=QLineEdit(self)
        self.rfisicos_t.setText('')
        self.rfisicos_t.setFont(QFont('Bond',8))
        self.rfisicos_t.move(20,155)
        self.rfisicos_t.setFixedSize(750,20)

        self.rpsicologicos_l=QLabel(self)
        self.rpsicologicos_l.setText('Requisitos Psicologicos')
        self.rpsicologicos_l.setFont(QFont('Bond',10))
        self.rpsicologicos_l.move(20,178)
        self.rpsicologicos_t=QLineEdit(self)
        self.rpsicologicos_t.setText('')
        self.rpsicologicos_t.setFont(QFont('Bond',8))
        self.rpsicologicos_t.move(20,196)
        self.rpsicologicos_t.setFixedSize(750,20)

        self.responsabilidades_l=QLabel(self)
        self.responsabilidades_l.setText('Responsabilidades')
        self.responsabilidades_l.setFont(QFont('Bond',10))
        self.responsabilidades_l.move(20,218)
        self.responsabilidades_t=QLineEdit(self)
        self.responsabilidades_t.setText('')
        self.responsabilidades_t.setFont(QFont('Bond',8))
        self.responsabilidades_t.move(20,236)
        self.responsabilidades_t.setFixedSize(750,20)

        self.condiciones_l=QLabel(self)
        self.condiciones_l.setText('Condiciones de Trabajo')
        self.condiciones_l.setFont(QFont('Bond',10))
        self.condiciones_l.move(20,258)
        self.condiciones_t=QLineEdit(self)
        self.condiciones_t.setText('')
        self.condiciones_t.setFont(QFont('Bond',8))
        self.condiciones_t.move(20,273)
        self.condiciones_t.setFixedSize(750,20)

        self.idiomas_l=QLabel(self)
        self.idiomas_l.setText('Idiomas')
        self.idiomas_l.setFont(QFont('Bond',10))
        self.idiomas_l.move(20,298)
        self.idiomast_t=QLineEdit(self)
        self.idiomast_t.setText('')
        self.idiomast_t.setFont(QFont('Bond',8))
        self.idiomast_t.move(20,316)
        self.idiomast_t.setFixedSize(400,20)

        self.habilidades_l=QLabel(self)
        self.habilidades_l.setText('Habilidades')
        self.habilidades_l.setFont(QFont('Bond',10))
        self.habilidades_l.move(425,298)
        self.habilidades_t=QLineEdit(self)
        self.habilidades_t.setText('')
        self.habilidades_t.setFont(QFont('Bond',8))
        self.habilidades_t.move(425,316)
        self.habilidades_t.setFixedSize(345,20)

        self.botona_pag=QPushButton(self)
        self.botona_pag.setText('Salir')
        self.botona_pag.setFont(QFont('Bond',8))
        self.botona_pag.move(370, 350)
        self.botona_pag.setFixedSize(120, 25)

        self.botoncancelar=QPushButton(self)
        self.botoncancelar.setText('Regresar')
        self.botoncancelar.setFont(QFont('Bond',8))
        self.botoncancelar.move(110,350)
        self.botoncancelar.setFixedSize(70, 25)

class ventanaeditar(QWidget):
    def __init__(self):
        super(ventanaeditar, self).__init__()
        self.nom_l=QLabel(self)
        self.nom_l.setText('Nombre del Puesto')
        self.nom_l.setFont(QFont('Bond',10))
        self.nom_l.move(20,20)
        self.nom_t=QLineEdit(self)
        self.nom_t.setText('')
        self.nom_t.setFont(QFont('Bond',8))
        self.nom_t.move(20,40)
        self.nom_t.setFixedSize(750,20)

        self.codp_l=QLabel(self)
        self.codp_l.setText('Codigo de Puesto')
        self.codp_l.setFont(QFont('Bond',10))
        self.codp_l.move(20,60)
        self.codpt_t=QLineEdit(self)
        self.codpt_t.setText('')
        self.codpt_t.setFont(QFont('Bond',8))
        self.codpt_t.move(20,78)
        self.codpt_t.setFixedSize(400,20)

        self.area_l=QLabel(self)
        self.area_l.setText('Area de adscripcion')
        self.area_l.setFont(QFont('Bond',10))
        self.area_l.move(425,60)
        self.area_t=QLineEdit(self)
        self.area_t.setText('')
        self.area_t.setFont(QFont('Bond',8))
        self.area_t.move(425,78)
        self.area_t.setFixedSize(345,20)

        self.super_l=QLabel(self)
        self.super_l.setText('Puesto del Jefe Superior')
        self.super_l.setFont(QFont('Bond',10))
        self.super_l.move(20,100)
        self.super_t=QLineEdit(self)
        self.super_t.setText('')
        self.super_t.setFont(QFont('Bond',8))
        self.super_t.move(20,118)
        self.super_t.setFixedSize(750,20)

        self.jornada_l=QLabel(self)
        self.jornada_l.setText('Jornada')
        self.jornada_l.setFont(QFont('Bond',10))
        self.jornada_l.move(20,138)
        self.jornada_t=QLineEdit(self)
        self.jornada_t.setText('')
        self.jornada_t.setFont(QFont('Bond',8))
        self.jornada_t.move(20,155)
        self.jornada_t.setFixedSize(450,20)

        self.remuneracion_l=QLabel(self)
        self.remuneracion_l.setText('Remuneracion Mensual')
        self.remuneracion_l.setFont(QFont('Bond',10))
        self.remuneracion_l.move(475,138)
        self.remuneracion_t=QLineEdit(self)
        self.remuneracion_t.setText('')
        self.remuneracion_t.setFont(QFont('Bond',8))
        self.remuneracion_t.move(475,155)
        self.remuneracion_t.setFixedSize(295,20)

        self.prestaciones_l=QLabel(self)
        self.prestaciones_l.setText('Prestaciones')
        self.prestaciones_l.setFont(QFont('Bond',10))
        self.prestaciones_l.move(20,178)
        self.prestaciones_t=QLineEdit(self)
        self.prestaciones_t.setText('')
        self.prestaciones_t.setFont(QFont('Bond',8))
        self.prestaciones_t.move(20,196)
        self.prestaciones_t.setFixedSize(750,20)

        self.descripccion_l=QLabel(self)
        self.descripccion_l.setText('Descripcion General')
        self.descripccion_l.setFont(QFont('Bond',10))
        self.descripccion_l.move(20,218)
        self.descripccion_t=QLineEdit(self)
        self.descripccion_t.setText('')
        self.descripccion_t.setFont(QFont('Bond',8))
        self.descripccion_t.move(20,236)
        self.descripccion_t.setFixedSize(750,20)

        self.funciones_l=QLabel(self)
        self.funciones_l.setText('Funciones')
        self.funciones_l.setFont(QFont('Bond',10))
        self.funciones_l.move(20,258)
        self.funciones_t=QLineEdit(self)
        self.funciones_t.setText('')
        self.funciones_t.setFont(QFont('Bond',8))
        self.funciones_t.move(20,273)
        self.funciones_t.setFixedSize(750,20)

        self.edad_l=QLabel(self)
        self.edad_l.setText('Edad')
        self.edad_l.setFont(QFont('Bond',10))
        self.edad_l.move(20,298)
        self.edad_t=QLineEdit(self)
        self.edad_t.setText('')
        self.edad_t.setFont(QFont('Bond',8))
        self.edad_t.move(20,316)
        self.edad_t.setFixedSize(225,20)

        self.sexo_l=QLabel(self)
        self.sexo_l.setText('Sexo')
        self.sexo_l.setFont(QFont('Bond',10))
        self.sexo_l.move(255,298)
        self.sexo_t=QLineEdit(self)
        self.sexo_t.setText('')
        self.sexo_t.setFont(QFont('Bond',8))
        self.sexo_t.move(255,316)
        self.sexo_t.setFixedSize(225,20)

        self.civil_l=QLabel(self)
        self.civil_l.setText('Estado Civil')
        self.civil_l.setFont(QFont('Bond',10))
        self.civil_l.move(485,298)
        self.civil_t=QLineEdit(self)
        self.civil_t.setText('')
        self.civil_t.setFont(QFont('Bond',8))
        self.civil_t.move(485,316)
        self.civil_t.setFixedSize(283,20)

        self.escolaridad_l=QLabel(self)
        self.escolaridad_l.setText('Escolaridad')
        self.escolaridad_l.setFont(QFont('Bond',10))
        self.escolaridad_l.move(20,340)
        self.escolaridad_t=QLineEdit(self)
        self.escolaridad_t.setText('')
        self.escolaridad_t.setFont(QFont('Bond',8))
        self.escolaridad_t.move(20,358)
        self.escolaridad_t.setFixedSize(225,20)

        self.gradoa_l=QLabel(self)
        self.gradoa_l.setText('Grado Avance')
        self.gradoa_l.setFont(QFont('Bond',10))
        self.gradoa_l.move(255,340)
        self.gradoa_t=QLineEdit(self)
        self.gradoa_t.setText('')
        self.gradoa_t.setFont(QFont('Bond',8))
        self.gradoa_t.move(255,358)
        self.gradoa_t.setFixedSize(225,20)

        self.carrera_l=QLabel(self)
        self.carrera_l.setText('Carrera')
        self.carrera_l.setFont(QFont('Bond',10))
        self.carrera_l.move(485,340)
        self.carrera_t=QLineEdit(self)
        self.carrera_t.setText('')
        self.carrera_t.setFont(QFont('Bond',8))
        self.carrera_t.move(485,358)
        self.carrera_t.setFixedSize(283,20)

        self.botona_pag=QPushButton(self)
        self.botona_pag.setText('Continuar')
        self.botona_pag.setFont(QFont('Bond',8))
        self.botona_pag.move(370, 390)
        self.botona_pag.setFixedSize(70, 20)

        self.botoncancelar=QPushButton(self)
        self.botoncancelar.setText('Cancelar')
        self.botoncancelar.setFont(QFont('Bond',8))
        self.botoncancelar.move(110,390)
        self.botoncancelar.setFixedSize(70, 25)

class ventanaeditar2(QWidget):
    def __init__(self):
        super(ventanaeditar2, self).__init__()
        self.experiencia_l=QLabel(self)
        self.experiencia_l.setText('Experiencia')
        self.experiencia_l.setFont(QFont('Bond',10))
        self.experiencia_l.move(20,20)
        self.experiencia_t=QLineEdit(self)
        self.experiencia_t.setText('')
        self.experiencia_t.setFont(QFont('Bond',8))
        self.experiencia_t.move(20,40)
        self.experiencia_t.setFixedSize(750,20)

        self.conocimentos_l=QLabel(self)
        self.conocimentos_l.setText('Conocimentos')
        self.conocimentos_l.setFont(QFont('Bond',10))
        self.conocimentos_l.move(20,60)
        self.conocimentos_t=QLineEdit(self)
        self.conocimentos_t.setText('')
        self.conocimentos_t.setFont(QFont('Bond',8))
        self.conocimentos_t.move(20,78)
        self.conocimentos_t.setFixedSize(750,20)

        self.mequipo_l=QLabel(self)
        self.mequipo_l.setText('ManejoEquipo')
        self.mequipo_l.setFont(QFont('Bond',10))
        self.mequipo_l.move(20,100)
        self.mequipo_t=QLineEdit(self)
        self.mequipo_t.setText('')
        self.mequipo_t.setFont(QFont('Bond',8))
        self.mequipo_t.move(20,118)
        self.mequipo_t.setFixedSize(750,20)

        self.rfisicos_l=QLabel(self)
        self.rfisicos_l.setText('Requisitos Fisicos')
        self.rfisicos_l.setFont(QFont('Bond',10))
        self.rfisicos_l.move(20,138)
        self.rfisicos_t=QLineEdit(self)
        self.rfisicos_t.setText('')
        self.rfisicos_t.setFont(QFont('Bond',8))
        self.rfisicos_t.move(20,155)
        self.rfisicos_t.setFixedSize(750,20)

        self.rpsicologicos_l=QLabel(self)
        self.rpsicologicos_l.setText('Requisitos Psicologicos')
        self.rpsicologicos_l.setFont(QFont('Bond',10))
        self.rpsicologicos_l.move(20,178)
        self.rpsicologicos_t=QLineEdit(self)
        self.rpsicologicos_t.setText('')
        self.rpsicologicos_t.setFont(QFont('Bond',8))
        self.rpsicologicos_t.move(20,196)
        self.rpsicologicos_t.setFixedSize(750,20)

        self.responsabilidades_l=QLabel(self)
        self.responsabilidades_l.setText('Responsabilidades')
        self.responsabilidades_l.setFont(QFont('Bond',10))
        self.responsabilidades_l.move(20,218)
        self.responsabilidades_t=QLineEdit(self)
        self.responsabilidades_t.setText('')
        self.responsabilidades_t.setFont(QFont('Bond',8))
        self.responsabilidades_t.move(20,236)
        self.responsabilidades_t.setFixedSize(750,20)

        self.condiciones_l=QLabel(self)
        self.condiciones_l.setText('Condiciones de Trabajo')
        self.condiciones_l.setFont(QFont('Bond',10))
        self.condiciones_l.move(20,258)
        self.condiciones_t=QLineEdit(self)
        self.condiciones_t.setText('')
        self.condiciones_t.setFont(QFont('Bond',8))
        self.condiciones_t.move(20,273)
        self.condiciones_t.setFixedSize(750,20)

        self.idiomas_l=QLabel(self)
        self.idiomas_l.setText('Idiomas')
        self.idiomas_l.setFont(QFont('Bond',10))
        self.idiomas_l.move(20,298)
        self.idiomast_t=QLineEdit(self)
        self.idiomast_t.setText('')
        self.idiomast_t.setFont(QFont('Bond',8))
        self.idiomast_t.move(20,316)
        self.idiomast_t.setFixedSize(400,20)

        self.habilidades_l=QLabel(self)
        self.habilidades_l.setText('Habilidades')
        self.habilidades_l.setFont(QFont('Bond',10))
        self.habilidades_l.move(425,298)
        self.habilidades_t=QLineEdit(self)
        self.habilidades_t.setText('')
        self.habilidades_t.setFont(QFont('Bond',8))
        self.habilidades_t.move(425,316)
        self.habilidades_t.setFixedSize(345,20)

        self.botona_pag=QPushButton(self)
        self.botona_pag.setText('Guardar y Regresar')
        self.botona_pag.setFont(QFont('Bond',8))
        self.botona_pag.move(370, 350)
        self.botona_pag.setFixedSize(120, 25)

        self.botoncancelar=QPushButton(self)
        self.botoncancelar.setText('Regresar')
        self.botoncancelar.setFont(QFont('Bond',8))
        self.botoncancelar.move(110,350)
        self.botoncancelar.setFixedSize(70, 25)

class aplicacion(QMainWindow):
    def __init__(self):
        super(aplicacion, self).__init__()
        self.apilar=QStackedWidget(self)
        self.pag1=VPuesto()
        self.pag2=Pag2()
        self.pag3=Pag3()
        self.ventanad=ventanaDetalles()
        self.ventanad2=ventanadetalles2()
        self.ventanaedit=ventanaeditar()
        self.ventanaedit2=ventanaeditar2()
        self.apilar.addWidget(self.pag1)
        self.apilar.addWidget(self.pag2)
        self.apilar.addWidget(self.pag3)
        self.apilar.addWidget(self.ventanad)
        self.apilar.addWidget(self.ventanad2)
        self.apilar.addWidget(self.ventanaedit)
        self.apilar.addWidget(self.ventanaedit2)
        self.setCentralWidget(self.apilar)
        self.apilar.setCurrentWidget(self.pag1)
        self.inicializar()

    def inicializar(self):
        self.resize(1000, 800)
        self.setWindowTitle('Ventanas Puesto')
        self.conexiones()

    def conexiones(self):
        self.pag1.agregar.clicked.connect(self.pedir_contra)
        self.pag2.botona_pag.clicked.connect(self.cambioa_pag3)
        self.pag3.botona_pag.clicked.connect(self.cambioa_pag1)
        self.pag3.botonregreso.clicked.connect(self.cambioa_pag2)
        self.pag2.botoncancelar.clicked.connect(self.cancelar_puesto)
        self.pag1.detalles.clicked.connect(self.ventanaDet)
        self.ventanad.botoncancelar.clicked.connect(self.cambioa_pag11)
        self.ventanad.botona_pag.clicked.connect(self.ventanaDet2)
        self.ventanad2.botoncancelar.clicked.connect(self.ventanaDet)
        self.ventanad2.botona_pag.clicked.connect(self.cambioa_pag11)
        self.pag1.editar.clicked.connect(self.contraynombreP)
        self.ventanaedit.botoncancelar.clicked.connect(self.cambioa_pag11)
        self.ventanaedit.botona_pag.clicked.connect(self.ventanaedi2)
        self.ventanaedit2.botona_pag.clicked.connect(self.cambioa_pag111)
        self.ventanaedit2.botoncancelar.clicked.connect(self.aventanaedi)

    def cambioa_pag111(self):
        self.variables_pag3()
        self.pasoa_bd()
        self.apilar.setCurrentWidget(self.pag1)

    def ventanaedi2(self):
        self.variables_pag2()
        self.apilar.setCurrentWidget(self.ventanaedit2)

    def aventanaedi(self):
        self.apilar.setCurrentWidget(self.ventanaedit)

    def ventanaDet2(self):
        self.apilar.setCurrentWidget(self.ventanad2)

    def ventanaDet(self):
        self.apilar.setCurrentWidget(self.ventanad)

    def cancelar_puesto(self):
        self.pag1.borrar_cancelar()
        self.apilar.setCurrentWidget(self.pag1)

    def cambioa_pag11(self):
        self.apilar.setCurrentWidget(self.pag1)

    def cambioa_pag2(self):
        self.apilar.setCurrentWidget(self.pag2)
    
    def cambioa_pag3(self):
        self.apilar.setCurrentWidget(self.pag3)
        self.variables_pag2()

    def cambioa_pag1(self):
        nombre_puesto=self.pag2.nom_t.text()
        self.pag1.agregar_fila(nombre_puesto)
        self.apilar.setCurrentWidget(self.pag1)
        self.variables_pag3()
        self.pasoa_bd()
        self.pag2.limpiar()
        self.pag3.limpiar()    

    def contraynombreP(self):
        ventanaEDI=ventanaemeeditar(self.contraynombrecorrectos)
        ventanaEDI.exec()

    def contraynombrecorrectos(self):
        self.apilar.setCurrentWidget(self.ventanaedit)

    def pedir_contra(self):
        ventanac = ventanacontra(self.contracorrecta)
        ventanac.exec()

    def contracorrecta(self):
        self.apilar.setCurrentWidget(self.pag2)

    def variables_pag2(self):
        self.nombre=self.pag2.nom_t.text()
        self.codigo_puesto=self.pag2.codpt_t.text()
        self.area_adscripcion=self.pag2.area_t.text()
        self.puesto_jefe=self.pag2.super_t.text()
        self.Jornada=self.pag2.jornada_t.text()
        self.remuneracion=self.pag2.remuneracion_t.text()
        self.prestaciones=self.pag2.prestaciones_t.text()
        self.descripccion_general=self.pag2.descripccion_t.text()
        self.funcion=self.pag2.funciones_t.text()
        self.edad=self.pag2.edad_t.text()
        self.sexo=self.pag2.sexo_t.text()
        self.estado_civil=self.pag2.civil_t.text()
        self.escolaridad=self.pag2.escolaridad_t.text()
        self.grado_avance=self.pag2.gradoa_t.text()
        self.carrera=self.pag2.carrera_t.text()

    def variables_pag3(self):
        self.experienci=self.pag3.experiencia_t.text()
        self.conocimientos=self.pag3.conocimentos_t.text()
        self.manejo_equipo=self.pag3.mequipo_t.text()
        self.requisitosF=self.pag3.rfisicos_t.text()
        self.requisitosP=self.pag3.rpsicologicos_t.text()
        self.responsabilidades=self.pag3.responsabilidades_t.text()
        self.condiciones=self.pag3.condiciones_t.text()
        self.idiomas=self.pag3.idiomast_t.text()
        self.habilidades=self.pag3.habilidades_t.text()

    def pasoa_bd(self):
        pass

class ventanacontra(QDialog):
    def __init__(self, callback):
        super().__init__()
        self.callback = callback
        self.setWindowTitle('Contraseña')
        self.setFixedSize(250, 150) 
        etiqueta = QLabel('Ingrese la contraseña:', self)
        self.contra = QLineEdit(self)  
        verifica = QPushButton('Verificar', self)
        verifica.clicked.connect(self.verificacontra)
        layout = QVBoxLayout()
        layout.addWidget(etiqueta)
        layout.addWidget(self.contra)
        layout.addWidget(verifica)
        self.setLayout(layout)

    def verificacontra(self):
        if self.contra.text()=='Secret':
            print('si pasa')
            self.close()
            self.callback()
        else:
            QMessageBox.warning(self, 'Contraseña incorrecta', 'La contraseña es incorrecta. Inténtelo de nuevo.')

class ventanaemeeditar(QDialog):
    def __init__(self, callback):
        super().__init__()
        self.callback2= callback
        self.setWindowTitle('')
        self.setFixedSize(250, 150) 
        nombreP=QLabel('Ingrese el nombre del puesto a editar')
        self.nombre=QLineEdit(self)
        contral = QLabel('Ingrese la contraseña:', self)
        self.contra = QLineEdit(self)  
        verifica = QPushButton('Verificar', self)
        verifica.clicked.connect(self.verificacontraynombre)
        layout = QVBoxLayout()
        layout.addWidget(nombreP)
        layout.addWidget(self.nombre)
        layout.addWidget(contral)
        layout.addWidget(self.contra)
        layout.addWidget(verifica)
        self.setLayout(layout)

    def verificacontraynombre(self):
        if self.contra.text()=='Secret' and self.nombre.text()=='1':
            print('si pasa')
            self.close()
            self.callback2()
        else:
            QMessageBox.warning(self, 'Contraseña o id invalidos', 'Inténtelo de nuevo.')


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ventana = aplicacion()
    ventana.show()
    sys.exit(app.exec())
